name: Release Extension

on:
    push:
        branches:
            - main
        tags:
            - release

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - uses: lannonbr/vsce-action@master
              with:
                  args: 'publish -p $VSCE_TOKEN'
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
