name: Release Extension

on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: get-npm-version
          id: package
          uses: martinbeentjes/npm-get-version-action@v1.3.1
            
        - name: Check Package Version
          env:
            CURRENT_VERSION: ${{ steps.package-version.outputs.current-version}}
          run: |
            echo $CURRENT_VERSION
            
    release:
        runs-on: ubuntu-latest
        if: contains(github.ref, 'tag')
        steps:
            - uses: actions/checkout@v3

            - name: Use Node Version 16
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Get npm cache directory
              id: npm-cache-dir
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"

            - uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm ci
              if: steps.cache-npm-cache.outputs.cache-hit != 'true' || steps.cache-node-modules.outputs.cache-hit != 'true'

            - name: Build
              run: npm run build

            - uses: lannonbr/vsce-action@master
              with:
                  args: 'publish -p $VSCE_TOKEN'
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
